name = "helen-theme"
license = "MIT"
licenselink = "https://github.com/helen-website/helen-theme/blob/main/LICENSE"
description = "聽海倫講看脈專用主題"
homepage = "https://helen.tw"
tags = ["blog", "dark", "chinese", "medical"]
features = ["responsive", "dark-theme", "chinese"]
min_version = "0.80.0"

[author]
  name = "海倫"
  homepage = "https://helen.tw"
